{
  "formatVersion": "1.1",
  "component": {
    "group": "com.kj.memory_helper",
    "module": "memory_helper",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "memory_helper-1.0.0.aar",
          "url": "memory_helper-1.0.0.aar",
          "size": 64436,
          "sha512": "73e5880324f1e799385d792dbf661cbb29c2a8a7d1f283e4fbd8604c6baa6cf317560acafd3afd74bdd599ae4229b28b1a79edfd0340e77505ee92188627316f",
          "sha256": "4ecb0d64c5df663ec8e212f194049331d75511ba18c8a1a450461650dfeaa905",
          "sha1": "90a3443d270c357d3d640c6a92d2599881927535",
          "md5": "c7f70267adf5ab23b5d82c443c51eec1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.github.kbjay",
          "module": "epic",
          "version": {
            "requires": "v1.0.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "memory_helper-1.0.0.aar",
          "url": "memory_helper-1.0.0.aar",
          "size": 64436,
          "sha512": "73e5880324f1e799385d792dbf661cbb29c2a8a7d1f283e4fbd8604c6baa6cf317560acafd3afd74bdd599ae4229b28b1a79edfd0340e77505ee92188627316f",
          "sha256": "4ecb0d64c5df663ec8e212f194049331d75511ba18c8a1a450461650dfeaa905",
          "sha1": "90a3443d270c357d3d640c6a92d2599881927535",
          "md5": "c7f70267adf5ab23b5d82c443c51eec1"
        }
      ]
    }
  ]
}
